<?php

namespace AppBundle\Repository;

/**
 * MarwenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarwenRepository extends \Doctrine\ORM\EntityRepository
{
}
